# Generated by Django 5.2.9 on 2026-01-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
    ]
